### ISSUE TITLE
I immediately get 429 Error Too Many requests

### ISSUE THREAD

**Issue by ruevaughn** [ferreiraklet/AlineDownloader#2]
Even with the -p set to different levels I get Error: HTTP Error 429: Too Many Requests. Any suggestions?

**Comment by ferreiraklet** [comment]
Hi ruevaughn, I apreciate that you tested my tool.
The solution would be to use proxies in order to avoid google ban, however, since this tool project is descontinued, and I found a way to get urls from google more effectively, I don't pretend to update the tool.
Thanks @ruevaughn 

Regards,

fklet
